# 비지도학습

## PCA

In [2]:
!python --version

Python 3.10.9


In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

cancer = load_breast_cancer()

# df_1 = pd.DataFrame(cancer.data, columns=cancer.feature_names)
# df_2 = pd.DataFrame(cancer.target, columns=["cancer_type"])
# df = pd.concat([df_1, df_2], axis=1)

x_train, x_test, y_train, y_test = train_test_split(
    cancer.data,
    cancer.target,
    test_size=0.4,
    shuffle=True,
    stratify=cancer.target,
)

x_train

array([[1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
        5.905e-02],
       [1.234e+01, 1.227e+01, 7.894e+01, ..., 1.070e-01, 3.110e-01,
        7.592e-02],
       [1.496e+01, 1.910e+01, 9.703e+01, ..., 1.489e-01, 2.962e-01,
        8.472e-02],
       ...,
       [1.464e+01, 1.524e+01, 9.577e+01, ..., 1.397e-01, 3.151e-01,
        8.473e-02],
       [1.300e+01, 2.513e+01, 8.261e+01, ..., 5.921e-02, 2.306e-01,
        6.291e-02],
       [1.184e+01, 1.894e+01, 7.551e+01, ..., 6.913e-02, 2.535e-01,
        7.993e-02]])

In [23]:
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# 차원축소를 하기 전에는 무조건 데이터를 정규화 시켜야함. => 이거 안하면 분산이 왜곡됨.
scaler = StandardScaler()
scaled_data = scaler.fit_transform(x_train, y_train)
scaled_data

# n_components의 값이 0 ~ 1 사이면 열의 갯수를 자동으로 지정, 2 이상부터는 내가 직접 지정할 수 있음.
pca = PCA(n_components=0.5)
pca_data = pca.fit_transform(scaled_data)
pca_data[:5]

array([[ 3.72909936, -2.62208287],
       [ 2.80584604, -0.05291909],
       [ 1.71917504, -1.44737764],
       [-2.66925936, -0.71643184],
       [-3.48464401,  0.18953668]])

In [24]:
# 분산행렬 => 아래에서는 14.04300302,  5.19143981 값으로 두 개.
pca.explained_variance_

array([13.76938658,  5.30572305])

In [25]:
# 분산행렬의 비율 => 해당 값들이 데이터를 대표하는 비율
pca.explained_variance_ratio_

array([0.45763357, 0.17633879])

In [26]:
sum(pca.explained_variance_ratio_)

0.6339723630727053

In [ ]:
# pipeline으로도 가능. 근데 어차피 적정 n값 보려면 따로 돌려서 확인해야됨.
model = make_pipeline(
    StandardScaler(),
    PCA(n_components=0.5)
)